CELDEV-802 WebDavService
celements/celements-webdav pull request #1
Opened 2019-03-28 18:41 UTC by msladek

https://synjira.atlassian.net/browse/CELDEV-802

2019-03-29 14:32 UTC, fpichler requested changes
add implementation for `createDirectory`

2019-03-29 14:32 UTC, fpichler commented on src/main/java/com/celements/webdav/SardineAdapter.java
> +    } catch (SardineException exc) {
I think it is better to throw an exception in case the file does not exists. Similar to the Files.delete semantic of Java: https://docs.oracle.com/javase/tutorial/essential/io/delete.html
it is then easier for the client to decide if this is excepted and can be ignored or if this is a more dangerous situation which needs to be put to the user or logged as error (e.g. like a mutext-lock file got "lost").

2019-03-29 14:32 UTC, fpichler commented on src/main/java/com/celements/webdav/WebDavScriptService.java
> +  public boolean store(String filePath, Attachment attachment) {
suggestion:
- name the method for storing NOT existing files `create`
- name the method for storing existing files `store` -> creates a new version entry on WebDav server
- name the method which does not care if a file exists `createOrStore` -> creates a new version entry on WebDav server
- name the method which deletes if exists and recreates the file `overwrite` -> deletes history and creates a new initial version
in all cases throw exceptions if contract expectations are not met.

2019-03-29 14:35 UTC, fpichler commented
please add a Developer Documentation on www.open-celements.org

2019-04-01 08:41 UTC, ebeutler submitted a review, later dismissed
Rights checks are pretty rudimentary and might need to be redesigned / refined at a later point, but should be fine for first version

2019-04-01 08:41 UTC, ebeutler commented on src/main/java/com/celements/webdav/SardineAdapter.java
> +    } catch (SardineException exc) {
👍

2019-04-01 17:11 UTC, msladek commented
- introduced `WebDavConnection` which is loaded by `WebDavService#connect(remoteLogin)`
- improved exception handling, see `#throwResourceAccessException`
- renames and new methods
- improved rights check on a specific doc

2019-04-03 18:04 UTC, ebeutler approved these changes

2019-04-03 18:04 UTC, ebeutler commented on src/main/java/com/celements/webdav/SardineAdapter.java
> +      case 418: // I'm a teapot - happy April Fools' Day 2019 ;)
👍

2019-04-05 09:38 UTC, fpichler approved these changes

2019-04-05 09:50 UTC, merged